<a href="https://colab.research.google.com/github/Krishrdx/ML_to_GenAI_Journey/blob/main/Day_03_NumPy_Broadcasting_%26_Vectorization.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

How NumPy applies operations without loops — and why ML models depend on this.

1. Understand broadcasting rules clearly

2. Predict output shapes before running code

3. Write loop-free, ML-grade NumPy code

4. Avoid silent broadcasting bugs (very common)


In [1]:
import numpy as np

In [19]:
arr = np.array([1,2,3])

In [3]:
arr = arr + 6

In [4]:
print(arr)

[7 8 9]


Broadcasting rules:
📏 Rule 1: Compare shapes from the right.

📏 Rule 2:
Dimensions are compatible if:
they are equal, OR
one of them is 1,

Otherwise → ❌ Error

Rule 3 :

Scalar + Vector = vector { scalar will be treated as vector}
Vector + Vector should have same shape
Matrix + Vector (ML GOLD) can be done if shape criteria is correct.

In [10]:
b = np.array([2,4,6])

print(arr * b)

[14 32 54]


In [11]:
c = np.array([[1,2,3],[4,5,6]])

In [12]:
print(c + arr)

[[ 8 10 12]
 [11 13 15]]


✔ arr added to every row
📌 Used in neural networks

In [13]:
X = np.array([[1,2,3],[4,5,6]])
v = np.array([1,2])

X + v


ValueError: operands could not be broadcast together with shapes (2,3) (2,) 

ValueError: operands could not be broadcast together with shapes (2,3) (1,2)

To fix this error we need to reshape the vector!!

In [15]:
reshaped_v = v.reshape((2,1))

X + reshaped_v

array([[2, 3, 4],
       [6, 7, 8]])

VEctorization vs Loopint (time is less in vectorization and easy to execute)

In [29]:
result = []

for x in arr:
  result.append( x * 2)

In [30]:
result

[np.int64(2), np.int64(4), np.int64(6)]

In [31]:
result = arr * 2
result

array([2, 4, 6])

In [33]:
X = np.array([[1,3],
             [4,6],
             [3,9]])
X_mean = X.mean(axis=0)
X_std = X.std(axis=0)
X_norm = (X - X_mean) / X_std

In [34]:
array = np.array([1,2,3])

array_new = array + 100

print(array_new)

[101 102 103]


In [35]:
X = np.array([[1,2,3],
             [4,5,6]])
add = [10,20,30]

X_new = X + add

print(X_new)

[[11 22 33]
 [14 25 36]]


In [37]:
Y = np.array([[1,2],
              [3,4],
              [5,6]])

Y_mean = Y.mean(axis = 0)

Y_new = Y - Y_mean
print(Y_mean)
print(Y_new)

[3. 4.]
[[-2. -2.]
 [ 0.  0.]
 [ 2.  2.]]


1. Why broadcasting does not create actual copies?
- Broadcasting does not create actual copies because NumPy uses stride-based virtual expansion. The smaller array is logically repeated during computation without allocating new memory, which improves performance and memory efficiency.

2. Why axis matters in ML normalization?
- because it determines whether operations like mean and standard deviation are applied across samples or across features. Choosing the wrong axis leads to incorrect feature scaling and poor model performance.

3. Why vectorization is critical for GenAI workloads?
- because large-scale tensor operations must be executed efficiently. Vectorized code runs in optimized C/CUDA kernels, leverages SIMD and GPU parallelism, avoids Python overhead, and enables real-time training and inference.