<a href="https://colab.research.google.com/github/Krishrdx/ML_to_GenAI_Journey/blob/main/Month_01_Foundations/Week_01_NumPy/Day_06_Advanced_Numpy_and_Operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [6]:
A = np.array([
    [10, 11, 12],
    [20, 21, 22],
    [30, 31, 32],
    [40, 41, 42]
])

print(A[::2]). # Every 2nd Row && [start:stop:step]

[[10 11 12]
 [30 31 32]]


In [9]:
b = np.arange(1,10).reshape(3,3)
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [12]:
# Daigonal Elements

np.diag(b)

np.diag(b, k =1)

np.diag(b, k = -1)

array([4, 8])

Diagonals are HUGE in:

covariance matrices

attention weights

image kernels

###Boolean + Fancy Indexing

In [14]:
x = np.arange(1,100,6)

print(x[x>45])

[49 55 61 67 73 79 85 91 97]


In [16]:
x[[0,2,3]]

array([ 1, 13, 19])

###Masked Assignment

Useful for:

replacing all invalid values

clipping

cleaning datasets

In [18]:
arr = np.array([1, 5, -2, 9, -7])
arr[arr < 0] = 0
print(arr)

[1 5 0 9 0]


1. Select every 3rd row from a 6×3 matrix.

2. Select the first column of a matrix using slicing.

3. Select the last row using negative index.

4. Select diagonal of a 4×4 random matrix.

5. Replace all odd numbers with 0 in an array.

6. Extract all elements < 50 from an array.

7. Select rows 1, 3, 5 from a matrix.

8. Select columns 0 and 2 from a matrix.

9. Find the shape of diagonal extracted from a 5×5 matrix.

10. Create an array of size 10 and extract elements at positions [2, 5, 7].

In [22]:
mat = np.random.randint(1,190,(6,3))
print(mat)

[[ 24 150 149]
 [148 101   1]
 [ 56  78   4]
 [149   8   6]
 [121 140 137]
 [105 172  15]]


In [23]:
print(mat[::3])

[[ 24 150 149]
 [149   8   6]]


In [27]:
mat[:,0]

array([ 24, 148,  56, 149, 121, 105])

In [29]:
mat[-1:,:]    # [row control, col control]

array([[105, 172,  15]])

In [47]:
y = np.random.randint(1,179,(4,4))
print(y)

[[ 25  34  12 146]
 [ 30 106  35  88]
 [ 57   2 172  69]
 [138  60 174  29]]


In [48]:
np.diag(y)

array([ 25, 106, 172,  29])

In [50]:
arey = np.array([4, 5, -2, 9, -7])

arey[arey%2!= 0] = 0
print(arey)

[ 4  0 -2  0  0]


In [52]:
mat[mat<100].reshape(4,2)

array([[24,  1],
       [56, 78],
       [ 4,  8],
       [ 6, 15]])

In [53]:
mat[::2]

array([[ 24, 150, 149],
       [ 56,  78,   4],
       [121, 140, 137]])

In [64]:
mat[:,::2]

array([[ 24, 149],
       [148,   1],
       [ 56,   4],
       [149,   6],
       [121, 137],
       [105,  15]])

In [67]:
z = np.arange(1,26).reshape(5,5)

In [69]:
np.diag(z).shape

(5,)

In [79]:
p = np.random.randint(1,44, size = 10)
print(p)

p[[2,5,7]]

[35 10 24 21 37 23 27 11  9 25]


array([24, 23, 11])