<a href="https://colab.research.google.com/github/Krishrdx/ML_to_GenAI_Journey/blob/main/Month_01_Foundations/Week_01_NumPy/Day_01_NumPy_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

DAY 01 - Numpy Basics

In [5]:
import numpy as np

np.__version__

'2.0.2'

In [10]:
py_list = [1,2,3]
numpy_arr = np.array([1,2,3])

print(type(numpy_arr))
print(type(py_list))

<class 'numpy.ndarray'>
<class 'list'>


List → slow, flexible

Array → fast, fixed-type, vectorized

In [14]:
arr1 = np.array([[1,2,5,7,8],
                 [3,6,9,12,15]])

print("the shape of arr1", arr1.shape)
print("the dimension of arr1", arr1.ndim)
print("the size of arr1", arr1.size)
print("the data type of arr1", arr1.dtype)

the shape of arr1 (2, 5)
the dimension of arr1 2
the size of arr1 10
the data type of arr1 int64


controls speed + GPU usage

In [18]:
zeros = np.zeros((5,4))
ones = np.ones((4,5))
identity = np.eye(3)

print("zeros:", zeros)
print("ones:", ones)
print("identity:", identity)

zeros: [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
ones: [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
identity: [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


used everywhere in ML initialization.

In [20]:
ar = np.arange(0,13,3)

ls = np.linspace(0,13,3)

print("ar : ", ar)
print("ls : ", ls)

ar :  [ 0  3  6  9 12]
ls :  [ 0.   6.5 13. ]


arange ->	step-based

linspace ->	count-based

In [24]:
arr = np.arange(12)
reshaped = arr.reshape(4,3)

print(arr)
print(reshaped)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


Tensor reshaping is core of deep learning. ( Most IMP)


Questions (DIBY) -

1. Create a 4×4 zero matrix.

2. Create an array from 10 to 50 with step 5.

3. Create a 1D array of 16 elements

4. Reshape it into 4×4

5. Print its shape and dtype.

6. Create a 3D array of shape (2, 3, 4)
7. Print:
      ndim
      shape
      total elements

8. Why are NumPy arrays faster than lists?

9. Why fixed dtype is important for GPUs?

10. What happens if reshape dimensions don’t match?

In [27]:
#1.
zeroMatrix = np.zeros((4,4))
print(zeroMatrix)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [28]:
#2.
array = np.arange(10,50,5)

print(array)

[10 15 20 25 30 35 40 45]


In [35]:
#3.
arey = np.arange(16)
print(arey)

#4.
new_arey = arey.reshape(4,4)

print(new_arey)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [39]:
#5.
shape = new_arey.shape
print(shape)
new_arey.dtype

(4, 4)


dtype('int64')

In [48]:
#6.
matrix_3d = np.arange(0,48,2)
# print(matrix_3d)
matrix_3d.shape

reshaped_3d_matrix = matrix_3d.reshape(2,3,4)
print(reshaped)

[[[ 0  2  4  6]
  [ 8 10 12 14]
  [16 18 20 22]]

 [[24 26 28 30]
  [32 34 36 38]
  [40 42 44 46]]]


In [52]:
reshaped_3d_matrix.ndim
reshaped_3d_matrix.shape
reshaped_3d_matrix.size

24

- NUPMY better than Python Lists because
1. they are faster
2. they are fixed not flexible
3. They are vectorized

- The fixed dtype are impt for GPUs because
1. predictable Memory alignment and they dont vary with time that provides stability to the sys.
2. the computing will get faster.
3. Low Memory allocation will happen
4. Better Parllelization : All cores execute the same instruction simultaneously.

- If the reshaped dimensions are not matched it must throw an ValueError.
