<a href="https://colab.research.google.com/github/Krishrdx/ML_to_GenAI_Journey/blob/main/Month_01_Foundations/Week_01_NumPy/Day_04_NumPy_Linear_Algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

The Matrix Algebra

In [7]:
import numpy as np

ab = np.array([2,4,5])
bc = np.array([3,4,6])

print(np.dot(ab, bc))

a = np.array([[1,2,3],[4,5,6]])
b = np.array([[1,2],[3,4],[5,6]])

adotb = np.dot(a,b)

print(adotb)

52
[[22 28]
 [49 64]]


Used in:

similarity

attention scores

cosine similarity

In [27]:
x = np.array([[1,2],
              [3,4]])

y = np.array([[5,6],
              [7,8]])

print(np.matmul(x,y))
print(x@y)

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


** *Shape Rule: *(m × n) @ (n × p) = (m × p)**

Otherwise → ❌ Error

In [29]:
# TRANSPOSE - Important

mat = np.array([[1,2,3],[4,5,6]])
transpose = mat.T
print(transpose)

[[1 4]
 [2 5]
 [3 6]]


Used in:

gradients

covariance matrices

attention mechanisms

In [26]:
# Identity and Inverse Matrix:

Identity = np.eye(4)

print(Identity)

demo_mat = np.array([[-18,-2,-53],[4,5,-6],[70,-18,10]])

Inverse = np.linalg.inv(demo_mat) # it only exists when determinant of this matrix is NOT equals to ZERO

print(Inverse)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[-0.00238389  0.04003288  0.01138512]
 [-0.0189067   0.14508837 -0.01315249]
 [-0.01734484 -0.01907111 -0.00337032]]


In [30]:
# NORMS - L2 Norms (most used)

v = np.array([5,6])

norm = np.linalg.norm(v)

print(norm)

7.810249675906654


Used In:

regularization

gradient clipping

similarity metrics

# ML Connections
1. Linear Regression

y = X @ w + b

2. Neural Network

y = X @ w + b

3. GEN AI

Scores = Q @ K.T

In [36]:
v1 = np.arange(2,66,5)

v2 = np.arange(4,55,4)

print(v1)
print(v2)

v1dotv2 = np.dot(v1,v2) # The shapes should be same before the product.

print(v1dotv2)

[ 2  7 12 17 22 27 32 37 42 47 52 57 62]
[ 4  8 12 16 20 24 28 32 36 40 44 48 52]
15288


In [38]:
x = np.array([[3,6],
              [2,9],
              [4,4]])

y = np.array([[1,2,3,4],
              [6,5,4,9]])

xmatmuly = x@y # np.matmul(x,y)

print(xmatmuly)

[[39 36 33 66]
 [56 49 42 89]
 [28 28 28 52]]


In [43]:
v = np.array([[5,6],
             [7,9],
             [9,0]])

norm = np.linalg.norm(v)

print(norm)

16.492422502470642


Why matrix multiplication is order-sensitive?

Why inverse is rarely used in deep learning?

Why attention uses dot products?