<a href="https://colab.research.google.com/github/Krishrdx/ML_to_GenAI_Journey/blob/main/Month_01_Foundations/Week_01_NumPy/Day_02_NumPy_Indexing_Slicing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

DAY 02 - Indexing and Slicing

INDEXING


In [2]:
import numpy as np

arey = np.array([10,20,20,30,40,5])

print(arey[0])
print(arey[-1])

10
5


Indexing returns a scalar

O(1) time complexity

In [120]:
arr = np.array([10,2,20,3,30,4,40,5,50])

s = arr.size
l = len(arr)
print(s)


9


In [121]:
#first -
print(arr[0])

#middle -

print(arr[s//2]) # it can be variable

#last -

print(arr[-1])

10
30
50


In [116]:
mat = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

print(mat[0,2])

3


In [117]:
# Access element 8      - not solved
# Access entire second row
# Access entire first column

print(mat[2,1])

8


In [41]:
for i in range(1):
  for j in range(3):
    print(mat[1,j], end=" ")

4 5 6 

In [44]:
for i in range(3):
  for j in range(1):
    print(mat[i,0], end=" ")

1 4 7 

SLICING

In [113]:
arey = np.array([0,1,2,3,4,5,6,6,7,8,9])

print(arey[2:6])
print(arey[:4])
print(arey[::2])

even_arey = arey[arey % 2 == 0]

print(even_arey)

[2 3 4 5]
[0 1 2 3]
[0 2 4 6 7 9]
[0 2 4 6 6 8]


NumPy slicing returns a view, not a copy

In [59]:
# Extract even numbers
# Reverse the array

ary = np.array([0,1,2,3,4,5,6,7,8])

evn_ary = ary[::2]

print(evn_ary)
print(ary[::-1])

[0 2 4 6 8]
[8 7 6 5 4 3 2 1 0]


In [64]:
matt = np.array([[1,2,3],
                 [4,5,6],
                [7,8,9]])

print(matt[:2,1:])

print(mat[::2,::2])

[[2 3]
 [5 6]]
[[1 3]
 [7 9]]


BOOLEAN MASKING


In [68]:
arr = np.array([10,20,30,40,50])

mask = arr > 20

print(arr[mask], end=" ")
print(arr[arr>30])

[30 40 50] [40 50]


Feature filtering

Outlier removal

Dataset cleaning

In [72]:
arr = np.array([12, 45, 8, 30, 22, 5])
# 1. Greater than 20
# 2. Between 10 and 30

In [112]:
# print(arr[arr>20])

mask = arr > 10

mask2 = arr[mask] < 30

print(mask2)

# print(arr[ (arr < 30) & (arr > 10)])

[ True False False  True]


In [105]:
mat = np.array([
    [5, 12, 18],
    [25, 7, 30],
    [9, 20, 15]
])

mat[mat > 15] # flatten array

array([18, 25, 30, 20])

1. Why does boolean masking return a flattened array?
- Boolean masking is a form of advanced (fancy) indexing.

- Boolean masking returns a flattened array because it is a type of advanced indexing that selects individual elements rather than contiguous blocks. Since the selected elements may be scattered across the array, NumPy returns them as a 1D array.

2. Why slicing returns a view but fancy indexing returns a copy?
- Slicing returns a view because it accesses a contiguous block of memory without copying data. Fancy indexing selects arbitrary elements that may not be contiguous, so NumPy must create a new array, resulting in a copy.

3. Why vectorized masking is faster than loops?
- Vectorized masking is faster because it executes operations in optimized C code using SIMD and low-level memory access, avoiding Python interpreter overhead present in explicit loops.

In [126]:
scores = np.array([45, 78, 88, 32, 90, 60])

# 1. Select passing scores (>40)
# 2. Normalize selected scores between 0 and 1

top_scorers = scores > 40

print(scores[top_scorers])

print(top_scorers)

[45 78 88 90 60]
[ True  True  True False  True  True]
