<a href="https://colab.research.google.com/github/Krishrdx/ML_to_GenAI_Journey/blob/main/Month_01_Foundations/Week_01_NumPy/Day_05_NumPy_Random_Stats.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Day 05 - Numpy Random Stats

1.   Generate reproducible randomness

2. Understand distributions used in ML

3. Compute statistical measures correctly

4. Connect randomness to training, initialization, sampling



In [ ]:
import numpy as np

In [ ]:
# Seetting a seed - starting point for randomness.
# every run gives same weights.

x = np.random.seed(80)

print(x)

None


Same output every run → debuggable ML

In [ ]:
y = np.random.rand(4) # This is used to generate the random num BETWEEN 0 TO 1 ONLY.

print(y)

[0.84656149 0.07964548 0.50524609 0.0652865 ]


Uniform — good for weight initialization

Helps avoid exploding/vanishing gradients

Used in Xavier, He-init variations

Normal — good when we want weights centered around zero

Helps symmetry breaking

Used in deep learning libraries for kernels & linear layers

In [ ]:
# Uniform Distribution

z = np.random.rand(3,3)

print(z)

[[0.26682728 0.62113383 0.52914209]
 [0.13457995 0.51357812 0.18443987]
 [0.78533515 0.85397529 0.49423684]]


In [ ]:
# Normal (gaussian) Distribution

z_mat = np.random.randn(100)

print(z_mat)

[-1.53495196e-01 -2.69056960e-01  2.23136679e+00 -2.43476758e+00
  1.12726505e-01  3.70444537e-01  1.35963386e+00  5.01857207e-01
 -8.44213704e-01  9.76147160e-06  5.42352572e-01 -3.13508197e-01
  7.71011738e-01 -1.86809065e+00  1.73118467e+00  1.46767801e+00
 -3.35677339e-01  6.11340780e-01  4.79705919e-02 -8.29135289e-01
  8.77102184e-02  1.00036589e+00 -3.81092518e-01 -3.75669423e-01
 -7.44707629e-02  4.33496330e-01  1.27837923e+00 -6.34679305e-01
  5.08396243e-01  2.16116006e-01 -1.85861239e+00 -4.19316482e-01
 -1.32328898e-01 -3.95702397e-02  3.26003433e-01 -2.04032305e+00
  4.62555231e-02 -6.77675577e-01 -1.43943903e+00  5.24296430e-01
  7.35279576e-01 -6.53250268e-01  8.42456282e-01 -3.81516482e-01
  6.64890091e-02 -1.09873895e+00  1.58448706e+00 -2.65944946e+00
 -9.14526229e-02  6.95119605e-01 -2.03346655e+00 -1.89469265e-01
 -7.72186654e-02  8.24703005e-01  1.24821292e+00 -4.03892269e-01
 -1.38451867e+00  1.36723542e+00  1.21788563e+00 -4.62005348e-01
  3.50888494e-01  3.81866

Used in:

- weight initialization

- noise modeling

In [ ]:
rand_arr = np.random.randint(1,40, size=4)

print(rand_arr)

[ 7 39 25  7]


Sampling from array

In [ ]:
arey = np.array([1,2,3,4,5])
are_choic = np.random.choice(arey, size=4, replace = False)

print(are_choic)

[5 3 1 2]


In [ ]:
mean = are_choic.mean()
print(mean)

median = np.median(are_choic)
print(median)

std = np.std(are_choic)
print(std)

var = np.var(are_choic)
print(var)

2.75
2.5
1.479019945774904
2.1875


In [ ]:
x = np.array([[1,2,3,4],
              [5,43,6,7],
              [8,6,4,2],
              [44,55,66,77]])

print(x.mean(axis=0)) # Feature wise
print(x.mean(axis=1)) # Sample wise

[14.5  26.5  19.75 22.5 ]
[ 2.5  15.25  5.   60.5 ]


Normalization - max-min scaling and standardization

In [ ]:
max_min = x - x.min(axis=0)/(x.max(axis=0)-x.min(axis=0))

print(max_min)

stdiztn = (x - x.mean(axis=0))/x.std(axis=0)

print(stdiztn)

[[ 0.97674419  1.96226415  2.95238095  3.97333333]
 [ 4.97674419 42.96226415  5.95238095  6.97333333]
 [ 7.97674419  5.96226415  3.95238095  1.97333333]
 [43.97674419 54.96226415 65.95238095 76.97333333]]
[[-0.78434041 -1.06799699 -0.6267707  -0.58700587]
 [-0.55194325  0.71926328 -0.51451326 -0.49181573]
 [-0.37764538 -0.89363014 -0.58935156 -0.65046596]
 [ 1.71392904  1.24236385  1.73063553  1.72928755]]


### Weight initialization : The process of giving initial random values to model weights before training.

Why needed?

To break symmetry

To speed up convergence

To avoid vanishing/exploding gradients

To help the network learn properly

In [ ]:
#Weight Initialization

W = np.random.randn(128, 64) * 0.01
print(W)

[[-0.00766375 -0.00866768 -0.0086632  ...  0.00436967 -0.0030686
  -0.01856797]
 [ 0.01261842 -0.00962493  0.01846909 ...  0.00811276  0.01014584
   0.01093157]
 [ 0.01045343  0.0155062  -0.01722639 ... -0.00242331  0.00097699
  -0.00655909]
 ...
 [-0.01373046 -0.01018933  0.01009099 ... -0.00677312 -0.02156781
  -0.008638  ]
 [-0.01024449 -0.00094291  0.01386738 ... -0.00651569  0.0039054
  -0.00733154]
 [-0.00553715 -0.0093843   0.00333558 ... -0.00057555 -0.01873743
  -0.00697066]]


In [ ]:
# Data shuffling - It shuffles indexes of the array randomly.

np.random.permutation(len(x))

array([2, 3, 0, 1])

In [ ]:
print(np.random.rand(10))

print(np.random.randint(10,50, size=5))

[0.73901096 0.38757022 0.525141   0.66101336 0.33482591 0.49212224
 0.72142776 0.72883528 0.70160326 0.61283563]
[35 48 33 31 17]


In [ ]:
arey = np.array([69,88, 99, 66, 10,55, 70,40])

print(np.random.choice(arey,size=3, replace=False))

[10 88 55]


In [ ]:
y = np.array([[2,4,6],
          [6,8,10],
          [2,3,4]])

print(y.mean(axis=0))
print(y.std(axis=0))



[3.33333333 5.         6.66666667]
[1.88561808 2.1602469  2.49443826]


In [ ]:
min_max = y - y.min(axis=0)/(y.max(axis=0)-y.min(axis=0))

stdiztn = y-y.mean(axis=0)/y.std(axis=0)

print("the min_max scale normaization is: ", min_max, "and the standardization will be: ", stdiztn)

the min_max scale normaization is:  [[1.5        3.4        5.33333333]
 [5.5        7.4        9.33333333]
 [1.5        2.4        3.33333333]] and the standardization will be:  [[0.23223305 1.68544975 3.32738758]
 [4.23223305 5.68544975 7.32738758]
 [0.23223305 0.68544975 1.32738758]]


1. Why setting a random seed is important in ML experiments?
- To ensure reproducibility of results.

2. Why Gaussian distribution is preferred in weight initialization?
- Uniform:

Good for avoiding large weights

Used in Xavier-uniform, He-uniform

Stable during early training

Normal:

Works well with Gaussian assumptions

Used in deep nets for kernels

Good for ReLU with He-normal

3. Why normalization improves model convergence? Normalization makes training faster, stable, and more accurate — especially for deep learning.
- It keeps all features on similar scale

If one feature is in meters (0–10) and another is in rupees (0–10,00,000),
the model will focus more on the large-scale feature → learning becomes unstable.
It helps weights update uniformly.
Works extremely well for deep networks

Deep layers multiply values many times → unnormalized inputs create huge instability.