<a href="https://colab.research.google.com/github/Krishrdx/ML_to_GenAI_Journey/blob/main/Month_01_Foundations/Week_01_NumPy/Day_06_Advanced_Numpy_and_Operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [ ]:
A = np.array([
    [10, 11, 12],
    [20, 21, 22],
    [30, 31, 32],
    [40, 41, 42]
])

print(A[::2]). # Every 2nd Row && [start:stop:step]

[[10 11 12]
 [30 31 32]]


In [ ]:
b = np.arange(1,10).reshape(3,3)
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
# Daigonal Elements

np.diag(b)

np.diag(b, k =1)

np.diag(b, k = -1)

array([4, 8])

Diagonals are HUGE in:

covariance matrices

attention weights

image kernels

###Boolean + Fancy Indexing

In [ ]:
x = np.arange(1,100,6)

print(x[x>45])

[49 55 61 67 73 79 85 91 97]


In [ ]:
x[[0,2,3]]

array([ 1, 13, 19])

###Masked Assignment

Useful for:

replacing all invalid values

clipping

cleaning datasets

In [ ]:
arr = np.array([1, 5, -2, 9, -7])
arr[arr < 0] = 0
print(arr)

[1 5 0 9 0]


1. Select every 3rd row from a 6×3 matrix.

2. Select the first column of a matrix using slicing.

3. Select the last row using negative index.

4. Select diagonal of a 4×4 random matrix.

5. Replace all odd numbers with 0 in an array.

6. Extract all elements < 50 from an array.

7. Select rows 1, 3, 5 from a matrix.

8. Select columns 0 and 2 from a matrix.

9. Find the shape of diagonal extracted from a 5×5 matrix.

10. Create an array of size 10 and extract elements at positions [2, 5, 7].

In [ ]:
mat = np.random.randint(1,190,(6,3))
print(mat)

[[ 24 150 149]
 [148 101   1]
 [ 56  78   4]
 [149   8   6]
 [121 140 137]
 [105 172  15]]


In [ ]:
print(mat[::3])

[[ 24 150 149]
 [149   8   6]]


In [ ]:
mat[:,0]

array([ 24, 148,  56, 149, 121, 105])

In [ ]:
mat[-1:,:]    # [row control, col control]

array([[105, 172,  15]])

In [ ]:
y = np.random.randint(1,179,(4,4))
print(y)

[[ 25  34  12 146]
 [ 30 106  35  88]
 [ 57   2 172  69]
 [138  60 174  29]]


In [ ]:
np.diag(y)

array([ 25, 106, 172,  29])

In [ ]:
arey = np.array([4, 5, -2, 9, -7])

arey[arey%2!= 0] = 0
print(arey)

[ 4  0 -2  0  0]


In [ ]:
mat[mat<100].reshape(4,2)

array([[24,  1],
       [56, 78],
       [ 4,  8],
       [ 6, 15]])

In [ ]:
mat[::2]

array([[ 24, 150, 149],
       [ 56,  78,   4],
       [121, 140, 137]])

In [ ]:
mat[:,::2]

array([[ 24, 149],
       [148,   1],
       [ 56,   4],
       [149,   6],
       [121, 137],
       [105,  15]])

In [ ]:
z = np.arange(1,26).reshape(5,5)

In [ ]:
np.diag(z).shape

(5,)

In [ ]:
p = np.random.randint(1,44, size = 10)
print(p)

p[[2,5,7]]

[35 10 24 21 37 23 27 11  9 25]


array([24, 23, 11])

Select all even rows and odd columns from a 6×6 matrix.

Select anti-diagonal (bottom-left → top-right).

Replace all values > mean with mean value.

Extract only border elements of a 5×5 matrix.

Mask all values not divisible by 3.

Extract upper-triangle (excluding diagonal).

Extract lower-triangle (including diagonal).

Remove negative values without masking (use boolean).

Given two arrays of indices, extract intersection positions.

Extract all rows where the sum of row > 30.

In [101]:
matrix = np.random.randint(-10,40,(6,6))
print(matrix)

[[ 23  -3  39  16  -4 -10]
 [ 21  16   5  17  29  -8]
 [ 27  31  39  39  11  25]
 [  4  -9  16   8  31   4]
 [ 30  25  35  14   6  29]
 [ 16   5  26  23  -2   9]]


In [21]:
matrix[1::2, ::2]

array([[19,  8, 38],
       [10,  6, 11],
       [15, 12, 19]])

In [22]:
np.diag(matrix[::-1, :])

array([15, 22,  6, 32, 38,  7])

In [58]:
mean = matrix.mean()
print(mean)
print("the real matrix is ", matrix)
matrix[matrix > mean] = mean
print("the mean matrix is ", matrix)

16.11111111111111
the real matrix is  [[20  5 20 15 20 16]
 [20 11 20 20 19 17]
 [19 16 11 18  4 20]
 [20 20 20 16 18 13]
 [ 2 20 20 11 14  2]
 [17 16 20 20 20 20]]
the mean matrix is  [[16  5 16 15 16 16]
 [16 11 16 16 16 16]
 [16 16 11 16  4 16]
 [16 16 16 16 16 13]
 [ 2 16 16 11 14  2]
 [16 16 16 16 16 16]]


In [120]:
matrix5 = np.random.randint(-5,20,(5,5))
print(matrix5)

[[10  4 -2  5  3]
 [18 14 12  0 11]
 [ 9  2 18  2 17]
 [-5  1 17 -5  2]
 [19  7 -3  2  8]]


In [127]:

# Extract upper-triangle (excluding diagonal). not solved

matrix5[np.triu_indices(4,k=-1)]

array([10,  4, -2,  5, 18, 14, 12,  0,  2, 18,  2, 17, -5])

In [68]:
matrix5[matrix5%3 != 0]

array([16, 20,  8, 35,  8, 11,  8, 34, 35, 34, 23, 31,  4, 11,  7, 29, 20,
       35])

In [87]:
# matrix5[:4, :4]. #. not solved
matrix5[np.tril_indices(5,-1)]


array([30,  8, 34, 23, 31,  4, 29, 20, 35, 39])

In [80]:
matrix5[np.triu_indices(5)]

array([36, 21, 39, 16, 20,  8, 35,  8, 11, 35, 21, 34, 11,  7, 15])

In [114]:
matrix5[matrix5 < 0] = True

matrix5

array([[15,  9, 15,  5,  0],
       [ 6,  0,  6,  0,  0],
       [11,  0, 16, 14, 17],
       [16,  0,  0, 16,  0],
       [17,  2, 17,  0,  0]])

In [118]:
#Given two arrays of indices, extract intersection positions.

a = np.array([1,2,3,4,5])
b = np.array([1,3,5,7,9])

np.intersect1d(a,b)

array([1, 3, 5])

In [111]:
matrix5[matrix5.sum(axis=1) > 30]

array([[15,  9, 15,  5, -3],
       [11, -3, 16, 14, 17]])