<a href="https://colab.research.google.com/github/Krishrdx/ML_to_GenAI_Journey/blob/main/Month_01_Foundations/Week_01_NumPy/Day_04_NumPy_Linear_Algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Day 04 The Matrix Algebra

In [1]:
import numpy as np

ab = np.array([2,4,5])
bc = np.array([3,4,6])

print(np.dot(ab, bc))

a = np.array([[1,2,3],[4,5,6]])
b = np.array([[1,2],[3,4],[5,6]])

adotb = np.dot(a,b)

print(adotb)

52
[[22 28]
 [49 64]]


Used in:

similarity

- Dot product = how similar two vectors are.

If two vectors point in the same direction → large dot product,
If opposite → negative,
If perpendicular → dot = 0.

attention scores

cosine similarity

In [ ]:
x = np.array([[1,2],
              [3,4]])

y = np.array([[5,6],
              [7,8]])

print(np.matmul(x,y))
print(x@y)

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


** *Shape Rule: *(m × n) @ (n × p) = (m × p)**

Otherwise → ❌ Error

In [ ]:
# TRANSPOSE - Important

mat = np.array([[1,2,3],[4,5,6]])
transpose = mat.T
print(transpose)

[[1 4]
 [2 5]
 [3 6]]


Used in:

gradients

covariance matrices

attention mechanisms

In [ ]:
# Identity and Inverse Matrix:

Identity = np.eye(4)

print(Identity)

demo_mat = np.array([[-18,-2,-53],[4,5,-6],[70,-18,10]])

Inverse = np.linalg.inv(demo_mat) # it only exists when determinant of this matrix is NOT equals to ZERO

print(Inverse)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[-0.00238389  0.04003288  0.01138512]
 [-0.0189067   0.14508837 -0.01315249]
 [-0.01734484 -0.01907111 -0.00337032]]


Norm = size / length / magnitude of a vector.

In [ ]:
# NORMS - L2 Norms (most used) L2 regularization penalizes large weights smoothly, preventing overfitting and making the model generalize better.

v = np.array([5,6])

norm = np.linalg.norm(v)

print(norm)

7.810249675906654


Used In:

regularization

gradient clipping

similarity metrics

# ML Connections
1. Linear Regression

y = X @ w + b

2. Neural Network

y = X @ w + b

3. GEN AI

Scores = Q @ K.T

In [ ]:
v1 = np.arange(2,66,5)

v2 = np.arange(4,55,4)

print(v1)
print(v2)

v1dotv2 = np.dot(v1,v2) # The shapes should be same before the product.

print(v1dotv2)

[ 2  7 12 17 22 27 32 37 42 47 52 57 62]
[ 4  8 12 16 20 24 28 32 36 40 44 48 52]
15288


In [ ]:
x = np.array([[3,6],
              [2,9],
              [4,4]])

y = np.array([[1,2,3,4],
              [6,5,4,9]])

xmatmuly = x@y # np.matmul(x,y)

print(xmatmuly)

[[39 36 33 66]
 [56 49 42 89]
 [28 28 28 52]]


In [ ]:
v = np.array([[5,6],
             [7,9],
             [9,0]])

norm = np.linalg.norm(v)

print(norm)

16.492422502470642


1. Why matrix multiplication is order-sensitive?
- Because matrix multiplication is NOT commutative. A×B != B×A

2. Why inverse is rarely used in deep learning? (slow + unstable + useless for training)
- 1. Computationally expensive
Inverse of an n×n matrix has ~O(n³) complexity → very slow for large layers.

- 2. Numerically unstable

If the matrix is close to singular:
inverse becomes huge
gradients explode
training breaks

- 3. We don’t need the exact inverse

Optimization (SGD, Adam, RMSProp…) works by gradients, not by solving exact equations.
Instead of:
𝑊=𝑋−1𝑌W=X−1Y
Deep learning uses:
𝑊=𝑊−𝜂⋅∇
W=W−η⋅∇
- 4. Better, more stable alternatives exist
Cholesky
QR
Pseudo-inverse
Gradient descent steps

So, inverse is avoided unless absolutely necessary.
3. Why attention uses dot products?

- Dot product gives similarity FAST, -- score=Q⋅KT
Dot product measures how aligned two vectors are.
Large dot → strong attention
Small dot → weak attention

Dot product is extremely efficient on GPUs-- Dot products = matrix multiplication.
Matrix multiplication = optimized, parallelized, vectorized.

Dot product captures BOTH angle and magnitude.

In [3]:
v = [3, 4]

norm = np.linalg.norm(v)
print(norm)

5.0


In [4]:
x = [5, 0 , -2]

print(np.linalg.norm(x))

5.385164807134504


L1 encourages sparsity because its gradient is constant and pushes small weights to exactly zero.

L2 does NOT create sparsity.
L1 does.

✔ L1 → sparse weights
✔ L1 → feature selection
✔ L1 → many zeros

We use L2 normalization because:

Dot product depends on magnitude, but cosine similarity depends only on direction.
L2 normalization makes all vectors unit length, so similarity is determined only by angle.